### ISSUE TITLE
Use the ypes api

### ISSUE THREAD

**Issue by gioiliop7** [GrigorisLionis/Elektion-Data-Scraper#1]
You can use the api to scrape more data and organize the result with more data.
For example to get data from districts you can fetch from following links. You can find more from network tab at your browser.
For example:
http://ekloges-prev.singularlogic.eu/2023/may/stat/v/ep_60.js
http://ekloges-prev.singularlogic.eu/2023/may/dyn/v/ep_60.js
If you see the network tab you will see url for canditates, etc.

**Comment by GrigorisLionis** [comment]
Much, much appreciated. Did not know there was an API

**Comment by GrigorisLionis** [comment]
API usage implemented.
Not sure if there is an API for all levels

**Comment by gioiliop7** [comment]
It has api for all the levels

- Candidates
- Regions
- Cities
- Abroad countries
- Abroad continents
- 300 names that take seat in parliament
- Parties

All that levels have endpoints (some have two)
You can find them with navigate the network tab in your browser while been in the page see the requests in every page.
